### PR TITLE
Sanitization, settings as array, conditional enqueue

### PR DESCRIPTION
**Pull request by boospot**
Hi James,

Its Rao abid from BooSpot team,

I have put together a pull request for your review.

This pull request does following:

**SANITIZE**
========
Sanitize the input on options save. You may view the details in method `settings_validate()` Code is commented and mostly self explanatory. Fields are sanitized with these methods:

- without specifying any sanitization callback, then fields will be sanitized on the basis of their type, for  instance, `number` is sanitized as `$value = ( is_numeric( $value ) ) ? $value : 0;` and `checkbox` is sanitized as `$value = ( (int) $value === 1 ) ? 1 : '';` complete details can be seen in method: `get_sanitized_field_value_by_type()`
- by specifying sanitize callback function name in field fonfig like:
```
array(
	'id'          => 'text',
	'title'       => 'Text',
	'desc'        => 'This is a description.',
	'placeholder' => 'This is a placeholder.',
	'type'        => 'text',
	'default'     => 'This is default',
	'sanitize'    => 'sanitize_text_field'
),
```
- if someone want to not use default sanitization, he can configure `'sanitize'    => 'no'` in fields config array.

**SETTINGS BY ARRAY**
========
Now user can pass the settings array directly in constructor without having to add a settings file. all that you need to do is pass `false` as first parameter to constructor.
for instance:

```
$settings_array = array(
	'option_group' => 'gf_select_form',
	'tabs'         => array(
		array(
			'id'    => 'tab_1',
			'title' => __( 'Tab 1' ),
		),
		array(
			'id'    => 'tab_2',
			'title' => __( 'Tab 2' ),
		),
	),
	'sections'     => array(
		array(
			'tab_id'        => 'tab_1',
			'section_id'    => 'section_1',
			'section_title' => 'Section 1',
			'section_order' => 10,
			'fields'        => array(
				array(
					'id'          => 'text',
					'title'       => 'Text',
					'desc'        => 'This is a description.',
					'placeholder' => 'This is a placeholder.',
					'type'        => 'text',
					'default'     => 'This is default',
					'sanitize'    => 'sanitize_text_field'
				),
				array(
					'id'      => 'number',
					'title'   => 'Number',
					'desc'    => 'This is a description.',
					'type'    => 'number',
					'default' => 10,
				),
			)
		),
		array(
			'tab_id'        => 'tab_2',
			'section_id'    => 'section_2',
			'section_title' => 'Section 2',
			'section_order' => 10,
			'fields'        => array(
				array(
					'id'      => 'text-3',
					'title'   => 'Text',
					'desc'    => 'This is a description.',
					'type'    => 'text',
					'default' => 'This is default',
				),
			),
		),
	),
);

$this->wpsf = new WordPressSettingsFramework( false, false, $settings_array );
```
Notice the `'option_group'` can optionally be passed in the config array as well.

**FUTURE PLAN**
==========
1. I can update the documentation as well if you are willing to incorporate this pull request.
2. Further, i plan to include admin menu related settings to `$settings_array` as well instead of separately calling `$this->wpsf->add_settings_page()`
3. Calls to CDNs should be removed and `'jquery-ui-css'` should be included in the assets as WordPress plugin review team does not feel 

Do let me know your thoughts on this and feel free to ask if anything is in doubt or need further clarification.

### CODE REVIEW

**Comment by jamesckemp** [comment]
@boospot Great work!

Setting up with an array instead of a settings file is a great addition.

1. Yes, please update the docs within this PR. 
2. I was thinking the same thing today. it feels like an unnecessary step at the moment.
3. Yes, good idea. I like the loading of assets only if the field is used, too.

I will test this out in the coming weeks and approve as soon as possible.

**Comment by boospot** [comment]
@jamesckemp 

Thank you for consideration. i forgot add the following to my comment: 

4. I have added a "media" type field as well, that calls the default wordpress media uploader window. Existing 'file' field is not working properly and also calling the old iframe for upload. check `generate_media_field()` method for details. it saves wordpress media id in settings. 
5. color field is saving fine but displaying the default configured in the field config array. 
6. why `'jquery-ui-css'` and `'thickbox'` scripts are loaded, could not get the idea.
7. timepicker and datepicker fields do not work if no `datepicker` is empty array in config, but if we put any config, it starts displaying, so maybe updating js could do the trick.

*Not Working*
```
array(
	'id'         => 'date',
	'title'      => 'Date Picker',
	'desc'       => 'yyyy-mm-dd',
	'type'       => 'date',
	'datepicker' => array()
),
```

*Working*
```
array(
	'id'         => 'date',
	'title'      => 'Date Picker',
	'desc'       => 'yyyy-mm-dd',
	'type'       => 'date',
	'datepicker' => array(
		'dateFormat' => "yy-mm-dd",
	), 
),
```
Can i make commits to my fork for document edits and still incorporate in this pull request?

**Comment by boospot** [comment]
I am going to add Array as first parameter instead of introducing a 3rd parameter, shall open a pull request  later.

**Comment by boospot** [comment]
New commits are made to forked repo with updates. Please check

**Comment by jamesckemp** [comment]
Hey, sorry - not had time to look at it yet. Will do ASAP

**Comment by jamesckemp** [comment]
Hey, sorry for the long delay on this. I have some time to look into it now, but I'd prefer for each feature to be submitted as separate PRs to make the code review easier.

Appreciate your efforts with it so far!

**Comment by boospot** [comment]
As you wish, if you dont want to add the sanitization to this, its all your choice.

**Pull request closed without merging**
